
import React from 'react';
import { Notification, RideHistory } from './types';

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    type: 'arrival',
    title: 'Arrivée à destination',
    message: 'Le bus a déposé Amine à l\'école en toute sécurité.',
    time: '08:05',
    read: false,
  },
  {
    id: '2',
    type: 'delay',
    title: 'Retard estimé',
    message: 'Embouteillage important sur l\'avenue H. Bourguiba. Retard estimé de 10 min.',
    time: '07:45',
    read: true,
  },
  {
    id: '3',
    type: 'info',
    title: 'Départ du bus',
    message: 'Le bus scolaire a commencé sa tournée.',
    time: '07:15',
    read: true,
  }
];

export const MOCK_HISTORY: RideHistory[] = [
  { id: '1', date: '25 Nov 2025', pickup: 'Maison', dropoff: 'École El Ghazala', status: 'completed', duration: '45 min' },
  { id: '2', date: '24 Nov 2025', pickup: 'Maison', dropoff: 'École El Ghazala', status: 'completed', duration: '42 min' },
  { id: '3', date: '23 Nov 2025', pickup: 'Maison', dropoff: 'École El Ghazala', status: 'absent', duration: '-' },
  { id: '4', date: '22 Nov 2025', pickup: 'Maison', dropoff: 'École El Ghazala', status: 'completed', duration: '40 min' },
];

export const THEME_COLOR = "purple"; 

export const TRANSLATIONS = {
  fr: {
    welcome: "Bienvenue",
    subtitle: "Connectez-vous pour suivre votre enfant.",
    phoneLabel: "Numéro de téléphone",
    continue: "Continuer",
    terms: "En continuant, vous acceptez nos Termes et Conditions.",
    child: "Enfant",
    estimatedTime: "Temps estimé",
    driver: "Chauffeur",
    route: "Itinéraire",
    notifications: "Notifications",
    profile: "Profil",
    general: "Général",
    childProfile: "Profil de l'enfant",
    history: "Historique des trajets",
    settings: "Paramètres",
    darkMode: "Mode Sombre",
    language: "Langue",
    logout: "Se déconnecter",
    save: "Enregistrer",
    edit: "Modifier",
    home: "Maison",
    school: "École",
    status_moving: "En route",
    status_delayed: "Retardé",
    map_standard: "Standard",
    map_satellite: "Satellite",
    map_dark: "Sombre",
    loginBtn: "Se connecter",
    signupBtn: "S'inscrire",
    searchNotif: "Rechercher une notification...",
    searchHistory: "Rechercher par date ou lieu...",
    searchMap: "Rechercher une adresse...",
    reportAbsence: "Signaler Absence",
    contactSchool: "Contacter École",
    shareRoute: "Partager Trajet",
    itinerary: "ITINÉRAIRE",
    routeToSchool: "Trajet vers École",
    accessCard: "Carte d'accès",
    scanBus: "Scan pour monter dans le bus",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    noAccount: "Pas encore de compte ?",
    alreadyMember: "Déjà membre ?",
    joinCommunity: "Rejoignez la communauté Hafla",
    createAccount: "Créer un compte",
    fullName: "Nom complet",
    childCode: "Code Enfant (Fourni par l'école)",
    minutes: "min",
    noHistory: "Aucun trajet trouvé.",
    noNotif: "Aucune notification trouvée.",
    completed: "Terminé",
    absent: "Absent",
    duration: "Durée",
    ageSuffix: "ans",
    classLabel: "Classe",
    grade3: "3ème Année",
    orContinueWith: "Ou continuer avec"
  },
  en: {
    welcome: "Welcome",
    subtitle: "Login to track your child.",
    phoneLabel: "Phone Number",
    continue: "Continue",
    terms: "By continuing, you agree to our Terms & Conditions.",
    child: "Child",
    estimatedTime: "Estimated Time",
    driver: "Driver",
    route: "Route",
    notifications: "Notifications",
    profile: "Profile",
    general: "General",
    childProfile: "Child Profile",
    history: "Ride History",
    settings: "Settings",
    darkMode: "Dark Mode",
    language: "Language",
    logout: "Logout",
    save: "Save",
    edit: "Edit",
    home: "Home",
    school: "School",
    status_moving: "On the way",
    status_delayed: "Delayed",
    map_standard: "Standard",
    map_satellite: "Satellite",
    map_dark: "Dark",
    loginBtn: "Login",
    signupBtn: "Sign Up",
    searchNotif: "Search notifications...",
    searchHistory: "Search by date or place...",
    searchMap: "Search for an address...",
    reportAbsence: "Report Absence",
    contactSchool: "Contact School",
    shareRoute: "Share Route",
    itinerary: "ITINERARY",
    routeToSchool: "Ride to School",
    accessCard: "Access Card",
    scanBus: "Scan to board the bus",
    password: "Password",
    forgotPassword: "Forgot password?",
    noAccount: "No account yet?",
    alreadyMember: "Already a member?",
    joinCommunity: "Join the Hafla community",
    createAccount: "Create an account",
    fullName: "Full Name",
    childCode: "Child Code (School provided)",
    minutes: "min",
    noHistory: "No rides found.",
    noNotif: "No notifications found.",
    completed: "Completed",
    absent: "Absent",
    duration: "Duration",
    ageSuffix: "years",
    classLabel: "Grade",
    grade3: "3rd Grade",
    orContinueWith: "Or continue with"
  },
  ar: {
    welcome: "مرحباً",
    subtitle: "قم بتسجيل الدخول لتتبع طفلك.",
    phoneLabel: "رقم الهاتف",
    continue: "متابعة",
    terms: "بالمتابعة، أنت توافق على الشروط والأحكام.",
    child: "الطفل",
    estimatedTime: "الوقت المقدر",
    driver: "السائق",
    route: "المسار",
    notifications: "الإشعارات",
    profile: "الملف الشخصي",
    general: "عام",
    childProfile: "ملف الطفل",
    history: "سجل الرحلات",
    settings: "الإعدادات",
    darkMode: "الوضع الداكن",
    language: "اللغة",
    logout: "تسجيل الخروج",
    save: "حفظ",
    edit: "تعديل",
    home: "المنزل",
    school: "المدرسة",
    status_moving: "في الطريق",
    status_delayed: "متأخر",
    map_standard: "قياسي",
    map_satellite: "قمر صناعي",
    map_dark: "داكن",
    loginBtn: "تسجيل الدخول",
    signupBtn: "إنشاء حساب",
    searchNotif: "البحث عن إشعار...",
    searchHistory: "البحث بالتاريخ أو المكان...",
    searchMap: "البحث عن عنوان...",
    reportAbsence: "تبليغ غياب",
    contactSchool: "اتصل بالمدرسة",
    shareRoute: "مشاركة الرحلة",
    itinerary: "خط الرحلة",
    routeToSchool: "رحلة المدرسة",
    accessCard: "بطاقة الدخول",
    scanBus: "امسح للصعود",
    password: "كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    noAccount: "ليس لديك حساب؟",
    alreadyMember: "لديك حساب بالفعل؟",
    joinCommunity: "انضم إلى مجتمع حفلة",
    createAccount: "إنشاء حساب",
    fullName: "الاسم الكامل",
    childCode: "رمز الطفل (من المدرسة)",
    minutes: "د",
    noHistory: "لم يتم العثور على رحلات.",
    noNotif: "لم يتم العثور على إشعارات.",
    completed: "مكتمل",
    absent: "غائب",
    duration: "المدة",
    ageSuffix: "سنوات",
    classLabel: "الصف",
    grade3: "السنة الثالثة",
    orContinueWith: "أو المتابعة باستخدام"
  }
};
